scrape_links_houses = [
    'https://www.homegate.ch/buy/house/canton-zurich/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-bern/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-lucerne/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-uri/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-schwyz/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-obwalden/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-nidwalden/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-glarus/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-zug/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-fribourg/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-solothurn/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-baselstadt/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-baselland/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-schaffhausen/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-appenzellausserrhoden/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-appenzellinnerrhoden/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-stgallen/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-graubuenden/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-aargau/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-thurgau/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-neuchatel/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-geneva/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-jura/matching-list?ipd=true',
    'https://www.homegate.ch/buy/house/canton-valais/matching-list?ipd=true&ai=&aj=1000000',
    'https://www.homegate.ch/buy/house/canton-valais/matching-list?ipd=true&ai=1000001&aj=',
    'https://www.homegate.ch/buy/house/canton-vaud/matching-list?ipd=true&ai=&aj=1800000',
    'https://www.homegate.ch/buy/house/canton-vaud/matching-list?ipd=true&ai=1800001&aj=',
    'https://www.homegate.ch/buy/house/canton-ticino/matching-list?ipd=true&ai=&aj=700000',
    'https://www.homegate.ch/buy/house/canton-ticino/matching-list?ipd=true&ai=700001&aj=1300000',
    'https://www.homegate.ch/buy/house/canton-ticino/matching-list?ipd=true&ai=1300001&aj=2200000',
    'https://www.homegate.ch/buy/house/canton-ticino/matching-list?ipd=true&ai=2200001&aj='
]

scrape_links_houses_rent = [
    'https://www.homegate.ch/rent/house/canton-zurich/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-bern/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-lucerne/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-uri/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-schwyz/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-obwalden/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-nidwalden/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-glarus/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-zug/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-fribourg/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-solothurn/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-baselstadt/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-baselland/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-schaffhausen/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-appenzellausserrhoden/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-appenzellinnerrhoden/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-stgallen/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-graubuenden/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-aargau/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-thurgau/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-neuchatel/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-geneva/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-jura/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-valais/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-vaud/matching-list?ipd=true',
    'https://www.homegate.ch/rent/house/canton-ticino/matching-list?ipd=true',
]

cantons_split_houses = {
    'valais': [1000000],
    'vaud': [1800000],
    'ticino': [700000, 1300000, 2200000],
}

cols_dict_details = {
    'property_id': 'VARCHAR(255) NOT NULL',
    'price': 'INTEGER',
    'page': 'INTEGER',
    'title': 'TEXT',
    'address': 'TEXT',
    'no_rooms': 'REAL',
    'living_area': 'INTEGER',
    'main_info': 'TEXT',
    'features_furnishings': 'TEXT',
    'advertiser': 'TEXT',
    'description': 'TEXT',
    'image_links': 'TEXT',
    'link': 'TEXT',

    'first_date_on_stock': 'DATE',
    'first_price': 'INTEGER',
    'stock': 'BOOLEAN',
    'sold': 'BOOLEAN',
    'new': 'BOOLEAN',
    'drops': 'INTEGER',
    'increases': 'INTEGER',
    'stock_date': 'DATE',
    'last_date_on_stock': 'DATE',
    'last_price': 'INTEGER',
    'dis_sold': 'INTEGER',
    'dis_stock': 'INTEGER',

    'balcony_terrace': 'BOOLEAN',
    'cable_tv': 'BOOLEAN',
    'child_friendly': 'BOOLEAN',
    'connected_land_for_building': 'BOOLEAN',
    'elevator': 'BOOLEAN',
    'fireplace': 'BOOLEAN',
    'garage': 'BOOLEAN',
    'mid_terrace_house': 'BOOLEAN',
    'minergie_certified': 'BOOLEAN',
    'minergie_construction': 'BOOLEAN',
    'new_building': 'BOOLEAN',
    'old_building': 'BOOLEAN',
    'parking_space': 'BOOLEAN',
    'pets_allowed': 'BOOLEAN',
    'quiet_neighborhood': 'BOOLEAN',
    'raised_ground_floor': 'BOOLEAN',
    'smoking_permitted': 'BOOLEAN',
    'swimming_pool': 'BOOLEAN',
    'view': 'BOOLEAN',
    'washing_machine': 'BOOLEAN',
    'wheelchair_access': 'BOOLEAN',

    'type': 'VARCHAR(255)',
    'no_of_rooms': 'REAL',
    'floor': 'TEXT',
    'surface_living': 'TEXT',
    'last_refurbishment': 'TEXT',
    'year_built': 'INTEGER',
    'number_of_apartments': 'INTEGER',
    'number_of_floors': 'INTEGER',
    'land_area': 'TEXT',
    'volume': 'TEXT',
    'floor_space': 'TEXT',
    'room_height': 'TEXT'
}

cols_dict = {
    'property_id': 'VARCHAR(255) NOT NULL',
    'price': 'INTEGER',
    'address': 'TEXT',
    'rooms': 'REAL',
    'living_space': 'INTEGER',
    'text': 'TEXT',
    'image_url': 'TEXT',
    'link': 'TEXT',
    'page': 'INTEGER',

    'first_date_on_stock': 'DATE',
    'first_price': 'INTEGER',
    'stock': 'BOOLEAN',
    'sold': 'BOOLEAN',
    'new': 'BOOLEAN',
    'drops': 'INTEGER',
    'increases': 'INTEGER',
    'stock_date': 'DATE',
    'last_date_on_stock': 'DATE',
    'last_price': 'INTEGER',
    'dis_sold': 'INTEGER',
    'dis_stock': 'INTEGER',
}

details_paths = {
    'title': 'h1.ListingTitle_spotlightTitle_ENVSi',
    'address': 'address.AddressDetails_address_i3koO',
    'no_rooms': 'div.SpotlightAttributesNumberOfRooms_value_TUMrd',
    'living_area': 'div.SpotlightAttributesLivingSpace_value_OiuVM',
    'main_info': 'div.CoreAttributes_coreAttributes_e2NAm',
    'features_furnishings': 'ul.FeaturesFurnishings_list_S54KV',
    'advertiser': 'p.ListerContactPhone_person_hZLKb',
    'description': 'div.Description_descriptionBody_AYyuy',
    'image_links': 'li.glide__slide img',
}

path_images = {
    'load_images_button': 'button.HgArrowButton_arrowButton_yXU5A',
    'image_count_1': '//*[@id="app"]/main/div/div[2]/div[1]/div[1]/div[1]/div[2]/div/div[1]/div/div/div[2]/button/span',
    'image_count_2': '//*[@id="app"]/main/div/div[2]/div[1]/div[2]/div[1]/div[2]/div/div[1]/div/div/div[2]/button/span',
}
