train_cols = [
    'rooms',
    'living_space',
    'sqm_per_room',
    'page',
    'has_image',
    'date_month',
    'date_year',
    'date_quarter',
    'latitude',
    'longitude',
    'location_size_big_city',
    'location_size_mid_city',
    'location_size_town',
    'location_size_village',

    'avg_price_sqm_by_canton_room_range',
    'avg_price_sqm_by_canton_living_space_range',
    # 'avg_price_stock_sqm_by_canton_room_range',
    # 'avg_price_stock_sqm_by_canton_living_space_range',
    # 'avg_price_sold_sqm_by_canton_room_range',
    # 'avg_price_sold_sqm_by_canton_living_space_range',

    'count_buy_by_canton_room_range',
    'count_buy_by_canton_living_space_range',
    # 'count_sold_buy_by_canton_room_range',
    # 'count_sold_buy_by_canton_living_space_range',
    # 'count_new_buy_by_canton_room_range',
    # 'count_new_buy_by_canton_living_space_range',
    # 'count_stock_buy_by_canton_room_range',
    # 'count_stock_buy_by_canton_living_space_range',

    'stockturn_buy_by_canton_room_range',
    'stockturn_buy_by_canton_living_space_range',
    'share_new_props_buy_by_canton_room_range',
    'share_new_props_buy_by_canton_living_space_range',

    'avg_net_drops_buy_by_canton_room_range',
    'avg_net_drops_buy_by_canton_living_space_range',
    'avg_net_increases_buy_by_canton_room_range',
    'avg_net_increases_buy_by_canton_living_space_range',
    'avg_sold_dis_buy_by_canton_room_range',
    'avg_sold_dis_buy_by_canton_living_space_range',
    'avg_stock_dis_buy_by_canton_room_range',
    'avg_stock_dis_buy_by_canton_living_space_range',

    'pct_diff_avg_buy_sold_vs_stock_sqm_by_canton_room_range',
    'pct_diff_avg_buy_sold_vs_stock_sqm_by_canton_living_space_range',



    'avg_rent_sqm_by_canton_room_range',
    'avg_rent_sqm_by_canton_living_space_range',
    # 'avg_rent_stock_sqm_by_canton_room_range',
    # 'avg_rent_stock_sqm_by_canton_living_space_range',
    # 'avg_rent_sold_sqm_by_canton_room_range',
    # 'avg_rent_sold_sqm_by_canton_living_space_range',

    'count_rent_by_canton_room_range',
    'count_rent_by_canton_living_space_range',
    # 'count_sold_rent_by_canton_room_range',
    # 'count_sold_rent_by_canton_living_space_range',
    # 'count_new_rent_by_canton_room_range',
    # 'count_new_rent_by_canton_living_space_range',
    # 'count_stock_rent_by_canton_room_range',
    # 'count_stock_rent_by_canton_living_space_range',

    'stockturn_rent_by_canton_room_range',
    'stockturn_rent_by_canton_living_space_range',
    'share_new_props_rent_by_canton_room_range',
    'share_new_props_rent_by_canton_living_space_range',

    'avg_net_drops_rent_by_canton_room_range',
    'avg_net_drops_rent_by_canton_living_space_range',
    'avg_net_increases_rent_by_canton_room_range',
    'avg_net_increases_rent_by_canton_living_space_range',
    'avg_sold_dis_rent_by_canton_room_range',
    'avg_sold_dis_rent_by_canton_living_space_range',
    'avg_stock_dis_rent_by_canton_room_range',
    'avg_stock_dis_rent_by_canton_living_space_range',

    'ratio_count_stock_rent_vs_buy_by_canton_room_range',
    'ratio_count_new_rent_vs_buy_by_canton_room_range',
    'ratio_count_sold_rent_vs_buy_by_canton_room_range',

    'share_rent_sqm_vs_price_sqm_by_canton_room_range',
    'share_rent_sqm_vs_price_sqm_by_canton_living_space_range',

    'pct_diff_avg_rent_sold_vs_stock_sqm_by_canton_room_range',
    'pct_diff_avg_rent_sold_vs_stock_sqm_by_canton_living_space_range',
]
